### PR TITLE
Configure CI 

### PR DESCRIPTION
**Pull request by scimetfoo**
Addresses #38

### CODE REVIEW

**Comment by kitallis** [comment]
@scimetfoo Could we add a build badge to the README?

**Comment by p-himik** [comment]
Just noticed something - this PR removes `deps.edn` and IIRC it will make it impossible to use Git coordinates of the library in projects that require it.

**Comment by scimetfoo** [comment]
@p-himik that’s a good point. Thanks for bringing it to notice. To use deps and lein together, we had to use a dependency resolution plugin (lein-tools-deps), which happens to rely on Clojure CLI tools. Because of Github Actions’ lack of support for Clojure CLI tools, I chose to get rid of this plugin and deps in the favour of using lein alone. Since we aren’t very heavily reliant on lein, and git coordinates seems to have a more compelling need for this project, I think we’ll get rid of lein in the favour of deps instead.

**Comment by kitallis** [comment]
@scimetfoo I believe this is ready to be merged, wdyt?

**Comment by kitallis** [comment]
@scimetfoo I'm making changes for this to run CI via `deps` now, since lein doesn't exist.

**Comment by kitallis** [comment]
@scimetfoo I think this works now and the build is green, feel to approve, squash and merge.

**Review by kitallis — APPROVED** [review]
i like this code

**Pull request merged**
